In [1]:
#library imports
import torch
import torch.nn as nn
import pandas as pd
import numpy as np
import string
from torch.nn.utils.rnn import pack_padded_sequence, pad_packed_sequence


In [2]:
x = torch.tensor([[1,2, 12,34, 56,78, 90,800],
                 [12,45, 99,67, 6,23, 77,82],
                 [3,24, 6,99, 12,56, 21,22]])

In [3]:
embedding = nn.Embedding(100, 4, padding_idx=0)
try:
    embedding(x)
except Exception as e:
    print("!!!!!! EXCEPTION",e)
#because embedding size is 100 and x has 800
#out of bounds for embedding

!!!!!! EXCEPTION index out of range at c:\a\w\1\s\tmp_conda_3.7_070403\conda\conda-bld\pytorch-cpu_1550387224787\work\aten\src\th\generic/THTensorEvenMoreMath.cpp:191


In [4]:
x = torch.tensor([[1,2, 12,34, 56,78, 90,80],
                 [12,45, 99,67, 6,23, 77,82],
                 [3,24, 6,99, 12,56, 21,22]])

In [5]:
embedding = nn.Embedding(100, 4, padding_idx=0)
lstm = nn.LSTM(input_size=4, hidden_size=4, num_layers=1, batch_first=True)

In [6]:
out1 = embedding(x)
out2 = lstm(out1)

In [7]:
#output of embedding layer
print(out1.shape)
print(out1)
#3 rows
#8 elements at each row
#4 embedding dimension

torch.Size([3, 8, 4])
tensor([[[ 0.1213,  0.6394,  0.4453,  0.0614],
         [-1.9590, -0.9193,  0.0855, -0.0672],
         [ 2.6248, -0.9895, -0.7465, -1.3162],
         [ 1.0287, -0.6980,  0.2701,  1.4103],
         [-0.0537,  0.3637, -0.8051, -0.0898],
         [ 0.8725, -0.9162,  0.9327,  0.7268],
         [-1.2243,  0.2799,  1.0548, -0.6815],
         [ 1.3256, -0.8312,  0.9003,  0.0614]],

        [[ 2.6248, -0.9895, -0.7465, -1.3162],
         [ 0.9697,  0.6942,  0.5068, -0.0855],
         [-0.8117, -0.9648, -1.3316,  1.1491],
         [-0.2162, -0.0378, -0.1016, -0.7394],
         [-0.2051,  0.3395,  2.0863,  1.1382],
         [-0.5041,  0.8226, -0.9456, -1.6709],
         [-1.5181, -1.1178,  1.1388, -0.2758],
         [ 0.4595,  0.1748, -0.9778, -1.9548]],

        [[-0.4661, -0.4087, -0.6473,  0.3290],
         [ 0.6733, -1.5643,  1.2827, -0.0660],
         [-0.2051,  0.3395,  2.0863,  1.1382],
         [-0.8117, -0.9648, -1.3316,  1.1491],
         [ 2.6248, -0.9895, -0.746

In [8]:
out, (ht, ct) = out2


In [9]:
print(out.shape)
print(out)
#3 rows
#8 elements at each row
#4 embedding dimension

torch.Size([3, 8, 4])
tensor([[[ 3.5475e-02,  9.9870e-02,  6.1752e-02,  5.3854e-02],
         [ 1.3702e-01,  1.2307e-01, -7.2537e-02, -5.8814e-02],
         [ 3.9210e-02,  1.2114e-02, -2.2412e-01, -1.3321e-02],
         [-6.8954e-02, -3.3705e-02,  8.0874e-02,  7.2888e-02],
         [-6.0908e-02, -4.4857e-02, -1.0079e-02,  1.3349e-01],
         [-4.5810e-02,  7.3287e-04,  1.0451e-01,  8.0864e-03],
         [ 1.1036e-01,  1.5329e-01,  2.4622e-02, -6.4384e-02],
         [ 6.0469e-02,  8.7474e-02,  1.1505e-01, -7.4289e-02]],

        [[-5.8297e-02, -1.6794e-01, -2.0020e-01,  6.3036e-02],
         [-6.2379e-02, -7.3569e-02,  6.6432e-02,  1.3760e-01],
         [-8.5328e-02, -8.2679e-02, -1.4774e-01,  4.3378e-02],
         [-1.3089e-02, -1.4716e-02, -2.1503e-01, -4.1143e-02],
         [ 1.8592e-01,  1.7598e-01, -1.4064e-02, -3.5401e-02],
         [ 5.9546e-02,  1.2239e-01, -2.3449e-01, -2.7957e-02],
         [ 1.4182e-01,  1.4159e-01, -2.2181e-01, -5.8176e-02],
         [ 4.8544e-02,  9.8363e

In [10]:
print(ht.shape)
print(ht)
#1 rows
#3 rows
#4 embedding dimension this is last generated state by lstm

torch.Size([1, 3, 4])
tensor([[[ 0.0605,  0.0875,  0.1151, -0.0743],
         [ 0.0485,  0.0984, -0.4254, -0.1161],
         [ 0.1847,  0.0997,  0.0034, -0.0060]]], grad_fn=<StackBackward>)


In [11]:
print(ct.shape)
print(ct)
#same as ht dimension cell state

torch.Size([1, 3, 4])
tensor([[[ 0.1227,  0.1917,  0.2185, -0.2041],
         [ 0.1718,  0.1517, -0.7322, -0.3243],
         [ 0.4528,  0.2935,  0.0116, -0.0205]]], grad_fn=<StackBackward>)
